import React, { useContext, useState } from 'react';
import { AppContext } from '../../context/AppContext';
import { Button, Card, CardContent, CardHeader, CardTitle, Input, Modal, Tabs, TabsList, TabsTrigger, TabsContent } from '../../components/ui';
import SignaturePad from '../../components/SignaturePad';

const EsignatureSettings: React.FC = () => {
    const { userProfile, updateUserProfile } = useContext(AppContext);
    const [isSignatureModalOpen, setSignatureModalOpen] = useState(false);
    const [isInitialsModalOpen, setInitialsModalOpen] = useState(false);

    const handleSaveSignature = (dataUrl: string) => {
        updateUserProfile({ signature: dataUrl });
        setSignatureModalOpen(false);
    };

    const handleSaveInitials = (dataUrl: string) => {
        updateUserProfile({ initials: dataUrl });
        setInitialsModalOpen(false);
    };

    return (
        <div className="space-y-8 max-w-4xl">
            <Tabs defaultValue="my-signature">
                <TabsList>
                    <TabsTrigger value="my-signature">My Signature</TabsTrigger>
                    <TabsTrigger value="pdf-signature">PDF Signature</TabsTrigger>
                </TabsList>
                <TabsContent value="my-signature">
                    <Card>
                        <CardHeader>
                            <CardTitle>Signature</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            {userProfile.signature ? (
                                <div className="p-4 border rounded-md bg-white">
                                    <img src={userProfile.signature} alt="Saved Signature" className="h-20" />
                                </div>
                            ) : <p className="text-sm text-slate-500">No signature saved.</p>}
                             <Button variant="secondary" onClick={() => setSignatureModalOpen(true)}>Update Signature</Button>
                        </CardContent>
                    </Card>
                    <Card className="mt-6">
                        <CardHeader>
                            <CardTitle>Initials</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            {userProfile.initials ? (
                                <div className="p-4 border rounded-md bg-white">
                                    <img src={userProfile.initials} alt="Saved Initials" className="h-20" />
                                </div>
                            ) : <p className="text-sm text-slate-500">No initials saved.</p>}
                            <Button variant="secondary" onClick={() => setInitialsModalOpen(true)}>Update Initials</Button>
                        </CardContent>
                    </Card>
                </TabsContent>
                <TabsContent value="pdf-signature">
                    <Card>
                        <CardHeader><CardTitle>PDF Signature</CardTitle></CardHeader>
                        <CardContent>
                            <div className="border-2 border-dashed border-slate-300 rounded-md p-8 text-center">
                                <svg xmlns="http://www.w3.org/2000/svg" className="mx-auto h-12 w-12 text-slate-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
                                <h3 className="mt-2 text-sm font-medium text-slate-900">Verify Signed PDF</h3>
                                <p className="mt-1 text-sm text-slate-500">Click to upload or drag and drop files</p>
                            </div>
                        </CardContent>
                    </Card>
                     <Card className="mt-6">
                        <CardHeader className="flex flex-row items-center justify-between">
                            <CardTitle>Signing Certificates</CardTitle>
                            <Button variant="secondary">+ Upload Cert</Button>
                        </CardHeader>
                        <CardContent>
                            <div className="border rounded-md">
                                <div className="p-4 flex items-center justify-between">
                                    <div>
                                        <p className="font-semibold">DocuSeal Self-Host Autogenerated</p>
                                        <p className="text-sm text-slate-500">Valid to: 15 September, 2125</p>
                                    </div>
                                    <Button variant="secondary" size="sm">Make Default</Button>
                                </div>
                                <div className="p-4 border-t flex items-center justify-between bg-slate-50">
                                    <div className="flex items-center">
                                        <p className="font-semibold mr-2">DocuSeal Trusted Signature</p>
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" className="w-4 h-4 text-slate-400"><path fillRule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14Zm.75-10.25a.75.75 0 0 0-1.5 0v2.5a.75.75 0 0 0 1.5 0v-2.5Zm0 5a.75.75 0 0 0-1.5 0v.01a.75.75 0 0 0 1.5 0V9.75Z" clipRule="evenodd" /></svg>
                                    </div>
                                    <div className="bg-amber-100 text-amber-800 text-xs font-bold px-3 py-1 rounded-md">UNLOCK WITH DOCUSEAL PRO</div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </TabsContent>
            </Tabs>

            <Modal isOpen={isSignatureModalOpen} onClose={() => setSignatureModalOpen(false)} title="Update Signature">
                <SignaturePad onSave={handleSaveSignature} onClose={() => setSignatureModalOpen(false)} />
            </Modal>
            <Modal isOpen={isInitialsModalOpen} onClose={() => setInitialsModalOpen(false)} title="Update Initials">
                <SignaturePad onSave={handleSaveInitials} onClose={() => setInitialsModalOpen(false)} />
            </Modal>
        </div>
    );
};

export default EsignatureSettings;